using BepInEx;
using BepInEx.Logging;
using BepInEx.Unity.IL2CPP;
using BigWalkArchipelago.Core;
using HarmonyLib;

// IMPORTANT NOTE ON REFERENCES:
// This project references the interop assembly generated by BepInEx IL2CPP
// (via Il2CppInterop) on the first launch of the game with BepInEx installed,
// never the "dummy" DLL generated by Il2CppInspectorRedux (used only for
// static code reading, not invokable at runtime). See lib/README.md.

namespace BigWalkArchipelago
{
    [BepInPlugin(PluginGuid, PluginName, PluginVersion)]
    public class Plugin : BasePlugin
    {
        // Also names the config file (BepInEx\config\<guid>.cfg) and
        // identifies the Harmony instance: changing it renames the .cfg, so
        // whatever was already typed into it (HostPort in particular) is
        // lost to a fresh file — rename the old one by hand if that happens.
        public const string PluginGuid = "com.grizfreak.bigwalk.archipelago";
        public const string PluginName = "Big Walk Archipelago";
        public const string PluginVersion = "0.1.0";

        // BasePlugin.Log is an INSTANCE property (confirmed via reflection on
        // BepInEx.Unity.IL2CPP.dll): we deliberately shadow it (`new`) with a
        // static field so we can write Plugin.Log.LogInfo(...) from any
        // static class (Harmony patches, etc.) without having to pass a
        // Plugin instance around everywhere.
        internal static new ManualLogSource Log;

        // Single hook point for Patches/: they call
        // Plugin.Reporter.ReportCheck(id) without knowing the implementation.
        internal static ICheckReporter Reporter { get; private set; }

        private Harmony _harmony;

        public override void Load()
        {
            Log = base.Log;
            Log.LogInfo($"{PluginName} v{PluginVersion} loaded (build {BuildFingerprint()}).");

            ModConfig.Bind(base.Config);

            Reporter = new Core.Net.ApReporter();

            _harmony = new Harmony(PluginGuid);
            _harmony.PatchAll();
            Patches.PlayerCountProceedLog.TryApply(_harmony);

            AddComponent<Core.Net.ApRuntime>();
            AddComponent<Core.Net.ApStatusOverlay>();
            AddComponent<Core.ArchDoorUnlocker>();
            AddComponent<Core.VariantGourdMapUnlocker>();
            AddComponent<Core.SecondEndingSphereUnlocker>();
            AddComponent<Core.CosmeticMonumentFillTracker>();
            AddComponent<Core.CosmeticGourdSpawnHandler>();
            AddComponent<Core.VanillaGadgetRemover>();
            AddComponent<Core.GadgetSpawnHandler>();
            AddComponent<Core.StaleHeldPropReleaser>();
            AddComponent<Core.PuzzleGourdRetirer>();
            AddComponent<Core.KeyColourPainter>();
            AddComponent<Core.Net.ModChannel>();
            AddComponent<Core.ModVersionLabel>();

            if (ModConfig.DebugModeEnabled.Value)
            {
                Debug.LoopbackGuest.DetectRole();
                Debug.LoopbackGuest.TryApply(_harmony);
                if (Debug.LoopbackGuest.IsGuest)
                    AddComponent<Debug.LoopbackGuestMonitor>();
                AddComponent<Debug.DebugHotkeys>();
                AddComponent<Debug.DebugGadgetRigDump>();
                AddComponent<Debug.DebugWorldLayoutDump>();
                Log.LogInfo($"[Debug] Debug module active (key: {ModConfig.ToggleFlightKey.Value}).");
            }

            Log.LogInfo("Harmony initialized.");
        }

        // The first 16 hex digits of this DLL's SHA-256: the same fingerprint
        // tools/deploy-mod.ps1 prints, so two logs can be matched to one
        // build. Added 2026-09-25, after a co-op test where the only way to
        // know which DLL the guest was running was to compare file times.
        private static string BuildFingerprint()
        {
            try
            {
                var path = typeof(Plugin).Assembly.Location;
                using var sha = System.Security.Cryptography.SHA256.Create();
                using var stream = System.IO.File.OpenRead(path);
                return System.BitConverter.ToString(sha.ComputeHash(stream)).Replace("-", "").Substring(0, 16);
            }
            catch (System.Exception)
            {
                return "unknown";
            }
        }
    }
}
