using BepInEx;
using BepInEx.Logging;
using BepInEx.Unity.IL2CPP;
using BigWalkArchipelago.Core;
using HarmonyLib;

// IMPORTANT NOTE ON REFERENCES:
// This project references the interop assembly generated by BepInEx IL2CPP
// (via Il2CppInterop) on the first launch of the game with BepInEx installed,
// never the "dummy" DLL generated by Il2CppInspectorRedux (used only for
// static code reading, not invokable at runtime). See lib/README.md.

namespace BigWalkArchipelago
{
    [BepInPlugin(PluginGuid, PluginName, PluginVersion)]
    public class Plugin : BasePlugin
    {
        public const string PluginGuid = "com.antonin.bigwalk.archipelago";
        public const string PluginName = "Big Walk Archipelago";
        public const string PluginVersion = "0.1.0";

        // BasePlugin.Log is an INSTANCE property (confirmed via reflection on
        // BepInEx.Unity.IL2CPP.dll): we deliberately shadow it (`new`) with a
        // static field so we can write Plugin.Log.LogInfo(...) from any
        // static class (Harmony patches, etc.) without having to pass a
        // Plugin instance around everywhere.
        internal static new ManualLogSource Log;

        // Single hook point for Patches/: they call
        // Plugin.Reporter.ReportCheck(id) without knowing the implementation.
        internal static ICheckReporter Reporter { get; private set; }

        private Harmony _harmony;

        public override void Load()
        {
            Log = base.Log;
            Log.LogInfo($"{PluginName} v{PluginVersion} loaded.");

            ModConfig.Bind(base.Config);

            Reporter = new Core.Net.ApReporter();

            _harmony = new Harmony(PluginGuid);
            _harmony.PatchAll();

            AddComponent<Core.Net.ApRuntime>();
            AddComponent<Core.Net.ApStatusOverlay>();
            AddComponent<Core.ArchDoorUnlocker>();
            AddComponent<Core.VariantGourdMapUnlocker>();
            AddComponent<Core.SecondEndingSphereUnlocker>();
            AddComponent<Core.CosmeticMonumentFillTracker>();

            if (ModConfig.DebugModeEnabled.Value)
            {
                AddComponent<Debug.DebugHotkeys>();
                Log.LogInfo($"[Debug] Debug module active (key: {ModConfig.ToggleFlightKey.Value}).");
            }

            Log.LogInfo("Harmony initialized.");
        }
    }
}
